export { default as AppMain } from './AppMain.vue'
export { default as Navbar } from './Navbar.vue'
// export { default as Settings } from './Settings'
export { default as Sidebar } from './Sidebar/Index.vue'
// export { default as TagsView } from './TagsView/index.vue'
export { default as SubTitle } from './SubTitle/index.vue'
